### PR TITLE
feat(thermocycler-refresh): Hold time tracking and more detailed GetPlateTemp response

### PR DESCRIPTION
**Pull request by fsinapi**
### Summary

Adds hold time tracking for plate targets. The firmware tracks the amount of time that has passed once the target temperature is hit. This doesn't actually control anything in the firmware, but it's reported back to the host computer.

- Updated the python utilities to grab new information from the GetPlateTemp response
- Tested on 1.4A unit, and unit tests were updated to check for new functionality

### CODE REVIEW

**Review by sfoster1 — CHANGES_REQUESTED** [review]
If the update rate specification is stable this looks good to me but it's a little... gross. I guess the stability is required for the control anyway, but at this point it seems like `update_rate` is only used to drive the time-left estimation; maybe getting the current tick, or using a freertos time-elapsed method, would be better?

**Comment by fsinapi** [comment]
@sfoster1 That change makes sense. The sample time is also used for ramp rate calculation and it's implied to match the PID controller's sample time. If we're getting the tick difference for each update then I think we should also update the PID controller to accept a variable sample time.

**Comment by sfoster1** [comment]
> @sfoster1 That change makes sense. The sample time is also used for ramp rate calculation and it's implied to match the PID controller's sample time. If we're getting the tick difference for each update then I think we should also update the PID controller to accept a variable sample time.

We definitely should at some point, though I see your point that maybe that shouldn't be now.

Oh, and I see where this value is SSOT'd from the control period in the freertos task, cool. Just didn't know where it's coming from.

**Review by sfoster1 — APPROVED** [review]
lgtm!

**Pull request merged**
